-- Matriz final stage_templates generada desde stage_templates_revision_v3.tsv
-- Esta version usa directamente los textos finales en posibles_match y tipo_respuesta.

CREATE TABLE IF NOT EXISTS stage_templates (
  id BIGSERIAL PRIMARY KEY,
  stage_actual VARCHAR(128) NOT NULL,
  posicion SMALLINT NULL,
  posibles_match TEXT NOT NULL,
  es_fallback BOOLEAN NOT NULL DEFAULT false,
  procesa_datos BOOLEAN NOT NULL DEFAULT false,
  dato_esperado VARCHAR(128) NULL,
  nuevo_stage VARCHAR(128) NOT NULL,
  tipo_respuesta TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stage_templates_stage_actual ON stage_templates(stage_actual);
CREATE INDEX IF NOT EXISTS idx_stage_templates_nuevo_stage ON stage_templates(nuevo_stage);
CREATE INDEX IF NOT EXISTS idx_stage_templates_activo ON stage_templates(activo);

-- Opcional si quieres recargar la matriz completa desde cero:
-- TRUNCATE TABLE stage_templates RESTART IDENTITY;

INSERT INTO stage_templates (
  stage_actual,
  posicion,
  posibles_match,
  es_fallback,
  procesa_datos,
  dato_esperado,
  nuevo_stage,
  tipo_respuesta,
  activo
) VALUES
  ('inicio', 1, 'mensaje que selecciona la opción de ver ofertas o expresa interés en conocer planes disponibles', false, false, NULL, 'intencion_ofertas', 'respuesta que presente la oferta inicial más adecuada para el caso y deje opciones claras para continuar', true),
  ('inicio', 2, 'mensaje que selecciona la opción de evaluar RUT, ya sea por número, nombre de la opción o una variante equivalente', false, false, NULL, 'intencion_requisitos', 'respuesta que solicite el RUT necesario para evaluar factibilidad comercial', true),
  ('inicio', 3, 'mensaje que selecciona la opción de hablar con un ejecutivo o solicita atención humana, ya sea por número, nombre de la opción o una variante equivalente', false, false, NULL, 'intencion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('inicio', NULL, 'mensaje que no permite asociar con claridad ninguna de las opciones esperadas en este stage', true, false, NULL, 'otras_solicitudes', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('intencion_ofertas', 1, 'mensaje que indica elección de la oferta presentada, ya sea por número, aceptación explícita o una variante equivalente', false, false, NULL, 'acepta_oferta', 'respuesta que solicite el RUT necesario para evaluar factibilidad comercial', true),
  ('intencion_ofertas', 2, 'mensaje que indica preferencia por atención humana, ya sea por número, solicitud directa o una variante equivalente', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('intencion_ofertas', 3, 'mensaje que indica intención de volver a las opciones anteriores, ya sea por número, texto directo o una variante equivalente', false, false, NULL, 'inicio', 'respuesta que vuelva a mostrar las opciones iniciales disponibles para continuar', true),
  ('intencion_ofertas', NULL, 'mensaje que expresa objeciones, dudas, condiciones o preguntas sobre la oferta presentada, incluyendo precio, características, comparación u otras variantes equivalentes', false, false, NULL, 'objeta_ofertas', 'respuesta que aborde la objeción o duda detectada y proponga la alternativa más conveniente según el caso', true),
  ('intencion_ofertas', NULL, 'mensaje que rechaza de forma expresa la oferta presentada o la continuidad de esa propuesta', false, false, NULL, 'no_acepta_oferta', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('intencion_ofertas', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'intencion_ofertas', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('acepta_oferta', NULL, 'mensaje que contiene un RUT chileno aparentemente válido', false, false, 'RUT CHILENO', 'entrega_datos_rut', 'respuesta breve de confirmación del dato recibido', true),
  ('acepta_oferta', NULL, 'mensaje que no contiene un RUT chileno identificable o lo entrega de forma insuficiente para usarlo', true, false, 'RUT CHILENO', 'acepta_oferta', 'respuesta que solicite corregir o completar el dato necesario para continuar', true),
  ('entrega_datos_rut', NULL, 'mensaje que confirma el RUT entregado previamente', false, true, 'RUT CHILENO', 'rut_factible', 'respuesta que informe el resultado de factibilidad comercial y presente las opciones disponibles para continuar', true),
  ('entrega_datos_rut', NULL, 'mensaje que confirma el RUT entregado previamente', false, true, 'RUT CHILENO', 'rut_no_factible', 'respuesta de cierre que explique el motivo de no factibilidad', true),
  ('entrega_datos_rut', NULL, 'mensaje que corrige o reemplaza el RUT entregado previamente', false, true, 'RUT CHILENO', 'rut_factible', 'respuesta que informe el resultado de factibilidad comercial y presente las opciones disponibles para continuar', true),
  ('entrega_datos_rut', NULL, 'mensaje que corrige o reemplaza el RUT entregado previamente', false, true, 'RUT CHILENO', 'rut_no_factible', 'respuesta de cierre que explique el motivo de no factibilidad', true),
  ('rut_factible', 1, 'mensaje que expresa intención de continuar con contratación de líneas nuevas', false, false, NULL, 'ofertas_alta', 'respuesta que resuma la oferta de línea nueva, explique próximos pasos y encamine la continuidad', true),
  ('rut_factible', 2, 'mensaje que expresa intención de continuar con contratación mediante portabilidad', false, false, NULL, 'ofertas_porta', 'respuesta que solicite las líneas a portar necesarias para evaluar su factibilidad', true),
  ('rut_factible', 3, 'mensaje que solicita que la conversación sea tomada por un ejecutivo o atención humana', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('rut_factible', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'rut_factible', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('ofertas_porta', NULL, 'mensaje que contiene una o más líneas telefónicas para evaluación o portabilidad', false, false, 'NUMERO TELEFONICO', 'entrega_datos_lineas', 'respuesta que solicite confirmar las líneas telefónicas que serán portadas', true),
  ('ofertas_porta', NULL, 'mensaje que no contiene líneas telefónicas identificables o las entrega de forma insuficiente', true, false, 'NUMERO TELEFONICO', 'ofertas_porta', 'respuesta que mencione la necesidad de contar con los nùmeros telefonicos a portar', true),
  ('entrega_datos_lineas', NULL, 'mensaje que confirma las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'lineas_factibles', 'respuesta que resuma la oferta de portabilidad, explique próximos pasos y encamine la continuidad', true),
  ('entrega_datos_lineas', NULL, 'mensaje que confirma las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'lineas_no_factibles', 'respuesta que proponga continuar con una oferta de línea nueva como alternativa', true),
  ('entrega_datos_lineas', NULL, 'mensaje que corrige o reemplaza las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'lineas_factibles', 'respuesta que resuma la oferta de portabilidad, explique próximos pasos y encamine la continuidad', true),
  ('entrega_datos_lineas', NULL, 'mensaje que corrige o reemplaza las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'lineas_no_factibles', 'respuesta que proponga continuar con una oferta de línea nueva como alternativa', true),
  ('lineas_no_factibles', 1, 'mensaje que indica aceptación de la alternativa de continuar con una línea nueva', false, false, NULL, 'ofertas_alta', 'respuesta que resuma la oferta de línea nueva, explique próximos pasos y encamine la continuidad', true),
  ('lineas_no_factibles', 2, 'mensaje que rechaza o posterga la decisión de contratación', false, false, NULL, 'cierre_no_exitoso', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('objeta_ofertas', 1, 'mensaje que indica elección de la oferta presentada, ya sea por número, aceptación explícita o una variante equivalente', false, false, NULL, 'acepta_oferta', 'respuesta que solicite el RUT necesario para evaluar factibilidad comercial', true),
  ('objeta_ofertas', 2, 'mensaje que indica preferencia por atención humana, ya sea por número, solicitud directa o una variante equivalente', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('objeta_ofertas', 3, 'mensaje que indica intención de volver a las opciones anteriores, ya sea por número, texto directo o una variante equivalente', false, false, NULL, 'inicio', 'respuesta que vuelva a mostrar las opciones iniciales disponibles para continuar', true),
  ('objeta_ofertas', NULL, 'mensaje que expresa objeciones, dudas, condiciones o preguntas sobre la oferta presentada, incluyendo precio, características, comparación u otras variantes equivalentes', false, false, NULL, 'objeta_ofertas', 'respuesta que aborde la objeción o duda detectada y proponga la alternativa más conveniente según el caso', true),
  ('objeta_ofertas', NULL, 'mensaje que rechaza de forma expresa la oferta presentada o la continuidad de esa propuesta', false, false, NULL, 'no_acepta_oferta', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('objeta_ofertas', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'intencion_ofertas', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('intencion_requisitos', NULL, 'mensaje que contiene un RUT chileno aparentemente válido', false, false, 'RUT CHILENO', 'requisitos_datos_rut', 'respuesta que solicite confirmar el RUT recibido antes de continuar', true),
  ('intencion_requisitos', NULL, 'mensaje que no contiene un RUT chileno identificable o lo entrega de forma insuficiente para usarlo', true, false, 'RUT CHILENO', 'intencion_requisitos', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('requisitos_datos_rut', NULL, 'mensaje que confirma como correcto el RUT validado previamente', false, true, 'RUT CHILENO', 'requisitos_rut_factible', 'respuesta que informe el resultado de factibilidad comercial y presente las opciones disponibles para continuar', true),
  ('requisitos_datos_rut', NULL, 'mensaje que corrige el RUT entregado anteriormente', false, true, 'RUT CHILENO', 'requisitos_rut_factible', 'respuesta que informe el resultado de factibilidad comercial y presente las opciones disponibles para continuar', true),
  ('requisitos_rut_factible', 1, 'mensaje que expresa intención de continuar con contratación de líneas nuevas', false, false, NULL, 'requisitos_oferta_alta', 'respuesta que presente una oferta de línea nueva y muestre opciones claras para continuar', true),
  ('requisitos_rut_factible', 2, 'mensaje que expresa intención de continuar con contratación mediante portabilidad', false, false, NULL, 'requisitos_oferta_porta', 'respuesta que solicite las líneas a portar necesarias para evaluar su factibilidad', true),
  ('requisitos_rut_factible', 3, 'mensaje que solicita que la conversación sea tomada por un ejecutivo o atención humana', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('requisitos_rut_factible', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'requisitos_rut_factible', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('requisitos_oferta_porta', NULL, 'mensaje que contiene una o más líneas telefónicas para portabilidad', false, true, 'NUMERO TELEFONICO', 'requisitos_datos_lineas', 'respuesta que solicite confirmar las líneas telefónicas que serán portadas', true),
  ('requisitos_oferta_porta', NULL, 'mensaje que no contiene ningún número telefónico identificable', true, true, 'NUMERO TELEFONICO', 'requisitos_oferta_porta', 'respuesta que mencione la necesidad de contar con los nùmeros telefonicos a portar', true),
  ('requisitos_datos_lineas', NULL, 'mensaje que confirma las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'requisitos_lineas_factibles', 'respuesta que presente una oferta de portabilidad y muestre opciones claras para continuar', true),
  ('requisitos_datos_lineas', NULL, 'mensaje que confirma las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'requisitos_lineas_no_factibles', 'respuesta que explique la no factibilidad de las líneas evaluadas y ofrezca continuar con línea nueva', true),
  ('requisitos_datos_lineas', NULL, 'mensaje que corrige o reemplaza las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'requisitos_lineas_factibles', 'respuesta que presente una oferta de portabilidad y muestre opciones claras para continuar', true),
  ('requisitos_datos_lineas', NULL, 'mensaje que corrige o reemplaza las líneas telefónicas entregadas previamente para evaluación', false, true, 'NUMERO TELEFONICO', 'requisitos_lineas_no_factibles', 'respuesta que explique la no factibilidad de las líneas evaluadas y ofrezca continuar con línea nueva', true),
  ('requisitos_lineas_no_factibles', 1, 'mensaje que indica aceptación de la alternativa de continuar con una línea nueva', false, false, NULL, 'requisitos_oferta_alta', 'respuesta que presente una oferta de línea nueva y muestre opciones claras para continuar', true),
  ('requisitos_lineas_no_factibles', 2, 'mensaje que rechaza o posterga la decisión de contratación', false, false, NULL, 'cierre_no_exitoso', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('otras_solicitudes', 1, 'mensaje que selecciona la opción de ver ofertas o expresa interés en conocer planes disponibles', false, false, NULL, 'intencion_ofertas', 'respuesta que presente la oferta inicial más adecuada para el caso y deje opciones claras para continuar', true),
  ('otras_solicitudes', 2, 'mensaje que selecciona la opción de evaluar RUT, ya sea por número, nombre de la opción o una variante equivalente', false, false, NULL, 'intencion_requisitos', 'respuesta que solicite el RUT necesario para evaluar factibilidad comercial', true),
  ('otras_solicitudes', 3, 'mensaje que selecciona la opción de hablar con un ejecutivo o solicita atención humana, ya sea por número, nombre de la opción o una variante equivalente', false, false, NULL, 'intencion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('otras_solicitudes', NULL, 'mensaje que no permite asociar con claridad ninguna de las opciones esperadas en este stage', false, false, NULL, 'cierre_no_exitoso', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('requisitos_oferta_alta', 1, 'mensaje que indica elección de la oferta presentada, ya sea por número, aceptación explícita o una variante equivalente', false, false, NULL, 'requisitos_acepta_alta', 'respuesta que resuma la oferta de línea nueva, explique próximos pasos y encamine la continuidad', true),
  ('requisitos_oferta_alta', 2, 'mensaje que indica preferencia por atención humana, ya sea por número, solicitud directa o una variante equivalente', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('requisitos_oferta_alta', 3, 'mensaje que indica intención de volver a las opciones anteriores, ya sea por número, texto directo o una variante equivalente', false, false, NULL, 'inicio', 'respuesta que vuelva a mostrar las opciones iniciales disponibles para continuar', true),
  ('requisitos_oferta_alta', NULL, 'mensaje que expresa objeciones, dudas, condiciones o preguntas sobre la oferta presentada, incluyendo precio, características, comparación u otras variantes equivalentes', false, false, NULL, 'requisitos_objeta_alta', 'respuesta que aborde la objeción o duda detectada y proponga la alternativa más conveniente según el caso', true),
  ('requisitos_oferta_alta', NULL, 'mensaje que rechaza de forma expresa la oferta presentada o la continuidad de esa propuesta', false, false, NULL, 'requisitos_rechaza_alta', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('requisitos_oferta_alta', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'requisitos_oferta_alta', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('requisitos_objeta_alta', 1, 'mensaje que indica elección de la oferta presentada, ya sea por número, aceptación explícita o una variante equivalente', false, false, NULL, 'requisitos_acepta_alta', 'respuesta que entregue una propuesta ajustada por negociación, con próximos pasos y continuidad', true),
  ('requisitos_objeta_alta', 2, 'mensaje que indica preferencia por atención humana, ya sea por número, solicitud directa o una variante equivalente', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('requisitos_objeta_alta', 3, 'mensaje que indica intención de volver a las opciones anteriores, ya sea por número, texto directo o una variante equivalente', false, false, NULL, 'inicio', 'respuesta que vuelva a mostrar las opciones iniciales disponibles para continuar', true),
  ('requisitos_objeta_alta', NULL, 'mensaje que rechaza de forma expresa la oferta presentada o la continuidad de esa propuesta', false, false, NULL, 'requisitos_rechaza_alta', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('requisitos_objeta_alta', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'requisitos_objeta_alta', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('requisitos_lineas_factibles', 1, 'mensaje que indica elección de la oferta presentada, ya sea por número, aceptación explícita o una variante equivalente', false, false, NULL, 'requisitos_acepta_porta', 'respuesta que resuma la oferta de portabilidad, explique próximos pasos y encamine la continuidad', true),
  ('requisitos_lineas_factibles', 2, 'mensaje que indica preferencia por atención humana, ya sea por número, solicitud directa o una variante equivalente', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('requisitos_lineas_factibles', 3, 'mensaje que indica intención de volver a las opciones anteriores, ya sea por número, texto directo o una variante equivalente', false, false, NULL, 'inicio', 'respuesta que vuelva a mostrar las opciones iniciales disponibles para continuar', true),
  ('requisitos_lineas_factibles', NULL, 'mensaje que expresa objeciones, dudas, condiciones o preguntas sobre la oferta presentada, incluyendo precio, características, comparación u otras variantes equivalentes', false, false, NULL, 'requisitos_objeta_porta', 'respuesta que aborde la objeción o duda detectada y proponga la alternativa más conveniente según el caso', true),
  ('requisitos_lineas_factibles', NULL, 'mensaje que rechaza de forma expresa la oferta presentada o la continuidad de esa propuesta', false, false, NULL, 'requisitos_rechaza_porta', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('requisitos_lineas_factibles', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'requisitos_lineas_factibles', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('requisitos_objeta_porta', 1, 'mensaje que indica elección de la oferta presentada, ya sea por número, aceptación explícita o una variante equivalente', false, false, NULL, 'requisitos_acepta_negociacion', 'respuesta que entregue una propuesta ajustada por negociación, con próximos pasos y continuidad', true),
  ('requisitos_objeta_porta', 2, 'mensaje que indica preferencia por atención humana, ya sea por número, solicitud directa o una variante equivalente', false, false, NULL, 'delegacion_humano', 'respuesta que indique la derivación a atención humana y la continuidad según horario de atención', true),
  ('requisitos_objeta_porta', 3, 'mensaje que indica intención de volver a las opciones anteriores, ya sea por número, texto directo o una variante equivalente', false, false, NULL, 'inicio', 'respuesta que vuelva a mostrar las opciones iniciales disponibles para continuar', true),
  ('requisitos_objeta_porta', NULL, 'mensaje que rechaza de forma expresa la oferta presentada o la continuidad de esa propuesta', false, false, NULL, 'requisitos_rechaza_porta', 'respuesta de cierre cordial sin continuidad comercial inmediata', true),
  ('requisitos_objeta_porta', NULL, 'mensaje ambiguo, insuficiente o difícil de asociar con una intención específica dentro de este stage', true, false, NULL, 'requisitos_objeta_porta', 'respuesta que reencauce la conversación hacia las opciones esperadas en este stage', true),
  ('requisitos_datos_rut', NULL, 'mensaje que confirma como correcto el RUT validado previamente', false, true, 'RUT CHILENO', 'requisitos_rut_no_factible', 'respuesta de cierre que explique el motivo de no factibilidad', true),
  ('requisitos_datos_rut', NULL, 'mensaje que corrige el RUT entregado anteriormente', false, true, 'RUT CHILENO', 'requisitos_rut_no_factible', 'respuesta de cierre que explique el motivo de no factibilidad', true);
