services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_local
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@llevatuplan.cl}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-<pgadmin_password>}
    ports:
      - "${HOST_BIND_IP:-100.121.39.83}:8080:80"
    networks:
      - npm_network

networks:
  npm_network:
    external: true
